version: "3.0"
services:
  bunworker:
      image: oven/bun
      container_name: bunworker
      working_dir: '/src/app/'
      ports:
        - 3987:3987
      volumes:
          - ./:/src/app/
      command: bash -c "bun ws.ts"